[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
>>>>>>> b54f735507efad81fe58afed6af87806d4b36129
