[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/gemini"
  to = "/.netlify/functions/gemini"
  status = 200

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/gemini"
  status = 200

[[redirects]]
  from = "/api/createUser"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200