services:
  # Backend API service
  - type: web
    name: sagradago-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: PORT
        value: 5001
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://sagradago.online
      - path: /*
        name: Access-Control-Allow-Methods
        value: GET, POST, OPTIONS
      - path: /*
        name: Access-Control-Allow-Headers
        value: Content-Type, Authorization

  # Frontend service
  - type: web
    name: sagradago-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: build
    routes:
      # Serve static files first
      - type: rewrite
        source: /static/*
        destination: /static/*
      # API rewrite rule
      - type: rewrite
        source: /api/:path*
        destination: http://sagradago-backend:5001/api/:path*
      # Handle client-side routing
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable